#!/bin/bash

pip3 install -r requirements.txt

mkdir -p /home/${USER}/.zcash-params
./fetch-params.sh

source pubkey.txt
if test -z "$pubkey"; then
  read -p "Enter your main pubkey: " pubkey
  if [ ${#pubkey} -ne 66 ]; then
    echo "Invalid pubkey length!"
  fi
  echo "pubkey=${pubkey}" > pubkey.txt
fi
pubkey_main=$pubkey

echo "Setting up .env file..."
USER_ID=$(id -u)
GROUP_ID=$(id -g)
echo "PUBKEY=${pubkey_main}" > .env
echo "USER_ID=${USER_ID}" >> .env
echo "GROUP_ID=${GROUP_ID}" >> .env

./update "$1" "$@"
