#!/bin/bash

script_path=$(dirname $(realpath $0))

source /home/${USER}/dPoW/iguana/pubkey.txt
if test -z "$pubkey"; then
  read -p "Enter your main pubkey: " pubkey
  if [ ${#pubkey} -ne 66 ]; then
    echo "Invalid pubkey length!"
  fi
  echo "pubkey=${pubkey}" > /home/${USER}/dPoW/iguana/pubkey.txt
fi

# Temp to unset docker_host_ip var
echo "Setting up .env file..."
USER_ID=$(id -u)
GROUP_ID=$(id -g)
echo "PUBKEY=${pubkey}" > .env
echo "USER_ID=${USER_ID}" >> .env
echo "GROUP_ID=${GROUP_ID}" >> .env

# Update repo
echo "Updating repository..."
git pull || sleep 5

# Update assetchains.json
rm assetchains.json
wget https://raw.githubusercontent.com/KomodoPlatform/dPoW/dev/iguana/assetchains.json

# Creating launch files
echo "Setting up launch files..."
./configure.py launch

# Updating docker-compose yaml
echo "Updating docker-compose.yml..."
./configure.py yaml
sed "s/USERNAME/${USER}/gi" -i "docker-compose.yml"

# Setting up conf files
echo "Setting up conf files..."
./configure.py confs

# Setting up cli wrappers
echo "Setting up cli wrappers..."
./configure.py clis


if [[ "$1" == "nobuild" ]]; then
    echo "Not building docker images..."
elif [ -z "$1" ]; then
    echo "Building docker images..."
    docker compose build $@ 
    ./stop
else
    echo "Building docker image: $1"
    docker compose build $1 $@ 
    ./stop $1
fi

mkdir -p  /home/$USER/.local/bin/
ln -sf ${script_path}/cli_wrappers/komodo-cli /home/$USER/.local/bin/komodo-cli
ln -sf ${script_path}/cli_wrappers/komodo-cli /home/$USER/.local/bin/kmd-cli
ln -sf ${script_path}/cli_wrappers/litecoin-cli /home/$USER/.local/bin/litecoin-cli
ln -sf ${script_path}/cli_wrappers/litecoin-cli /home/$USER/.local/bin/ltc-cli

./listassetchains | while read coin; do
    coin=$(echo $coin | awk '{print tolower($0)}')
    ln -sf ${script_path}/cli_wrappers/${coin}-cli /home/$USER/.local/bin/${coin}-cli
done
ln -sf ${script_path}/cli_wrappers/gleec_old-cli /home/$USER/.local/bin/gleec_old-cli

cp /home/$USER/.komodo/GLEEC_OLD/GLEEC.conf /home/$USER/.komodo/GLEEC_OLD/GLEEC_OLD.conf 

./start
