#!/bin/bash

# Update repo
echo "Updating repository..."
git pull || echo "No git pull failed! Fix the issue and try again..." && sleep 5

# Update assetchains.json
rm assetchains.json
wget https://raw.githubusercontent.com/KomodoPlatform/dPoW/master/iguana/assetchains.json

# Creating launch files
echo "Setting up launch files..."
./configure.py launch

# Initialising docker-compose yaml
echo "Updating docker-compose.yml..."
./configure.py yaml
sed "s/USERNAME/${USER}/gi" -i "docker-compose.yml"

# Setting up conf files
echo "Setting up conf files..."
./configure.py confs

# Setting up cli wrappers
echo "Setting up cli wrappers..."
./configure.py clis




if [[ "$1" == "nobuild" ]]; then
    echo "Not building docker images..."
elif [ -z "$1" ]; then
    echo "Building docker images..."
    docker compose build $@
    ./stop
else
    echo "Building docker image: $1"
    docker compose build $1 $@
    ./stop $1
fi

if [ -z "$1" ]; then
  echo "Update complete! Run ./start_main.sh $1 to launch the $1 daemon container."
else
  echo "Update complete! Run ./start_main.sh to launch the daemon containers."
fi